/*[UPDATE]1*/
CREATE TABLE SZO_CTK_CADASTRO_TICKETS(
  CTK_CODIGO INTEGER NOT NULL PRIMARY KEY,
  CTK_TIMESTAMP DATETIME,
  CTK_MD5 VARCHAR(60),
  CTK_DESCRICAO VARCHAR(40),
  CTK_VALOR NUMERIC(15,4),
  CTK_DOM BIT,
  CTK_SEG BIT,
  CTK_TER BIT,
  CTK_QUA BIT,
  CTK_QUI BIT,
  CTK_SEX BIT,
  CTK_SAB BIT,
  CTK_INATIVO BIT,
  CTK_SINCRONIZADO BIT
);

CREATE TABLE SZO_OPR_OPERADORES(
  OPR_CODIGO INTEGER NOT NULL PRIMARY KEY,
  OPR_TIMESTAMP DATETIME,
  OPR_MD5 VARCHAR(60),
  OPR_NOME VARCHAR(40),
  OPR_SENHA VARCHAR(60),
  OPR_GERENCIA BIT,
  OPR_CANCELAR_ITEM BIT,
  OPR_CANCELAR_CUPOM BIT,
  OPR_INATIVO BIT,
  OPR_SINCRONIZADO BIT
);

CREATE TABLE SZO_FPG_FORMA_PAGAMENTO(
  FPG_CODIGO INTEGER NOT NULL PRIMARY KEY,
  FPG_TIMESTAMP DATETIME,
  FPG_MD5 VARCHAR(60),
  FPG_DESCRICAO VARCHAR(40),
  FPG_INATIVO BIT,
  FPG_SINCRONIZADO BIT
);

CREATE TABLE SZO_MCX_MOVIMENTO_CAIXA(
  MCX_CODIGO INTEGER NOT NULL PRIMARY KEY,
  MCX_TIMESTAMP DATETIME,
  MCX_MD5 VARCHAR(60),
  MCX_IDENTIFICACAO VARCHAR(60),
  MCX_DATA DATETIME,
  MCX_MOVIMENTO DATETIME,
  MCX_TIPO VARCHAR(40),
  MCX_VALOR NUMERIC(15,4),
  MCX_SINCRONIZADO BIT
);

CREATE TABLE SZO_VDA_VENDA(
  VDA_CODIGO INTEGER NOT NULL PRIMARY KEY,
  VDA_TIMESTAMP DATETIME,
  VDA_MD5 VARCHAR(60),
  VDA_IDENTIFICACAO VARCHAR(60),
  VDA_OPR_MD5 VARCHAR(60),
  VDA_MOVIMENTO DATETIME,
  VDA_TOTAL NUMERIC(15,4),
  VDA_TOTAL_PAGO NUMERIC(15,4),
  VDA_TROCO NUMERIC(15,4),
  VDA_SINCRONIZADO BIT
);

CREATE TABLE SZO_VTK_VENDA_TICKETS(
  VTK_CODIGO INTEGER NOT NULL PRIMARY KEY,
  VTK_TIMESTAMP DATETIME,
  VTK_MD5 VARCHAR(60),
  VTK_IDENTIFICACAO VARCHAR(60),
  VTK_VDA_MD5 VARCHAR(60),
  VTK_OPR_MD5 VARCHAR(60),
  VTK_CTK_MD5 VARCHAR(60),
  VDA_MOVIMENTO DATETIME,
  VTK_DATA DATETIME,
  VTK_DESCRICAO VARCHAR(40),
  VTK_VALOR NUMERIC(15,4),
  VTK_SINCRONIZADO BIT
);

CREATE TABLE SZO_PGT_PAGAMENTO(
  PGT_CODIGO INTEGER NOT NULL PRIMARY KEY,
  PGT_TIMESTAMP DATETIME,
  PGT_MD5 VARCHAR(60),
  PGT_IDENTIFICACAO VARCHAR(60),
  PGT_VDA_MD5 VARCHAR(60),
  PGT_OPR_MD5 VARCHAR(60),
  PGT_FPG_MD5 VARCHAR(60),
  PGT_MOVIMENTO DATETIME,
  PGT_DESCRICAO VARCHAR(40),
  PGT_VALOR NUMERIC(15,4),
  PGT_SINCRONIZADO BIT
);

CREATE TABLE SZO_CFG_CONFIG(
  CFG_CODIGO INTEGER NOT NULL PRIMARY KEY,
  CFG_MOVIMENTO DATE,
  CFG_OPR_CODIGO INTEGER,
  CFG_IDENTIFICACAO VARCHAR(60),
  CFG_PRINTER_PORT VARCHAR(20),
  CFG_PRINTER_VELOCITY INTEGER
);
/*[UPDATE]2*/
ALTER TABLE SZO_CFG_CONFIG ADD CFG_IMPRIMIR_INDIVIDUAL BIT;
ALTER TABLE SZO_CTK_CADASTRO_TICKETS ADD CTK_ATALHO VARCHAR(20);
/*[UPDATE]3*/
CREATE VIEW SZO_VW_DATA_MOVIMENTO (DTMOVIMENTO, IDENTIFICACAO) AS
SELECT VDA_MOVIMENTO AS DTMOVIMENTO, VDA_IDENTIFICACAO AS IDENTIFICACAO FROM SZO_VDA_VENDA GROUP BY VDA_MOVIMENTO UNION ALL
SELECT MCX_MOVIMENTO AS DTMOVIMENTO, MCX_IDENTIFICACAO AS IDENTIFICACAO FROM SZO_MCX_MOVIMENTO_CAIXA GROUP BY MCX_MOVIMENTO;
/*[UPDATE]4*/
ALTER TABLE SZO_CFG_CONFIG ADD CFG_IMPRIMIR_SEMFORMATACAO BIT;