CREATE TABLE ATD_ATENDIMENTO(
  ATD_CODIGO INTEGER NOT NULL PRIMARY KEY IDENTITY,
  ATD_ABERTURA DATETIME DEFAULT GETDATE(),
  ATD_LOJA VARCHAR(60),
  ATD_ASSUNTO VARCHAR(40),
  ATD_GUICHE INTEGER,
  ATD_SENHA VARCHAR(20),
  ATD_PREFERENCIAL BIT,
  ATD_INICIO DATETIME,
  ATD_FIM DATETIME,
  ATD_CONCLUIDO BIT  
);